### ISSUE TITLE
最新版win10自带输入法没有效果

### ISSUE THREAD

**Issue by ghlcd** [zcodes/IMESupport#15]
Sublime Text Build 3176 x64，Windows10专业版版本号1809，自带输入法没有效果。IMESupport更新到最新的反而没有效果，之前的好好的，今天更新了GitHub上的最新的，不起作用了。

**Comment by RyanIPO** [comment]
我也一样。

**Comment by zcodes** [comment]
@ghlcd @RyanIPO 解决 #16， 更新一下看看是不是这个问题导致的

**Comment by RyanIPO** [comment]
@zcodes  谢谢大佬，已经可以了------我查了st3报错信息是爬虫没权限爬一个txt文件，你是怎么解决的呢？我们为啥会出现这种问题？

**Comment by RyanIPO** [comment]
@zcodes 我看了你的提交，引用了一个操作系统库，加了一行获取系统文件路径的代码。。。哎，python我就学了一个基础，想自己解决这样的问题能力不够啊

**Comment by zcodes** [comment]
@RyanIPO 看错误提示信息！！很明显是没有权限写入 font_name.txt 导致异常了，这个是由于 st 安装版（exe）在写入 font_name.txt 文件路径定位到了 st 的安装目录（C:\Program Files, 该目录有权限限制），把 font_name.txt 的路径搞确定（直接使用绝对路径）就可以了

**Comment by ghlcd** [comment]
> @ghlcd @RyanIPO 解决 #16， 更新一下看看是不是这个问题导致的

是这个问题，解决了。
