### ISSUE TITLE
3186 官方的是不是向下偏移了一行？

### ISSUE THREAD

**Issue by TomatoFryEggs** [zcodes/IMESupport#17]
RT

**Comment by TomatoFryEggs** [comment]
提了issue好久了都没有改~

**Comment by LiuQixuan** [comment]
sublime 3 官网最新不是3176么，你们从哪弄得3186

**Comment by TomatoFryEggs** [comment]
> sublime 3 官网最新不是3176么，你们从哪弄得3186

dev

**Comment by zcodes** [comment]
dev 没码了，看不了...

**Comment by TomatoFryEggs** [comment]
> dev 没码了，看不了...
https://www.macbl.com/app/development/sublime-text-3
这个里面的码可以用。

**Comment by zcodes** [comment]
@TomatoFryEggs 看了下 3.2 (Build 3200)，这个应该算是一种 Style 吧，好像是 IME 的接口在设置窗口位置的时候有这种方式来着，记不太清了

**Comment by TomatoFryEggs** [comment]
> @TomatoFryEggs 看了下 3.2 (Build 3200)，这个应该算是一种 Style 吧，好像是 IME 的接口在设置窗口位置的时候有这种方式来着，记不太清了

额，这恐怕是一种强迫症style~
