### ISSUE TITLE
重命名文件夹时出现了和sublime一样的输入框

### ISSUE THREAD

**Issue by derekxia1988** [zcodes/IMESupport#18]
![snipaste_2019-03-08_18-09-35](https://user-images.githubusercontent.com/28382254/54022391-59ab2400-41cd-11e9-8d28-2bd42202896c.png)
用了这个插件之后，sublime的中文输入跟随问题解决了，但是我发现我在桌面上新建的文件夹在重命名的时候出现了sublime的那个中文输入框。。。而且貌似只有桌面上的文件夹才有这个问题。

**Comment by zcodes** [comment]
@derekxia1988 你用的是最新的吗？

**Comment by derekxia1988** [comment]
我下的release里的，release里不是只有一版吗

**Comment by zcodes** [comment]
直接下master

**Comment by derekxia1988** [comment]
嗯嗯，我看你说了新版的sublime解决了IME的问题，不过我觉得用atom了，免费的。。。多谢

**Comment by zcodes** [comment]
@derekxia1988 你也可以尝试一下 VsCode

**Comment by derekxia1988** [comment]
vscode貌似挺重的，还能调试啥的，不过atom启动也不快，大概都跟核心有关吧。其实sublime挺好，就是太贵了。。。
