### ISSUE TITLE
安装之后打开搜狗输入法切换中文输入sublime失去响应卡死

### ISSUE THREAD

**Issue by shuohao** [zcodes/IMESupport#2]
搜狗输入法是8.8最新版，直接卡死cpu飙升

**Comment by lanternLucas** [comment]
同样的问题

**Comment by zsedcbm** [comment]
我也碰到了这个问题。

**Comment by zcodes** [comment]
装了搜狗试了一下，确实会假死，但不知道什么原因。这个插件是针对微软拼音输入法的，现在我也不知道如何对解决这个问题。（没发现搜狗相关的文档)

**Comment by zsedcbm** [comment]
重新安装回 市场中的IMESupport 偶尔会异常,大部分时间可以正常使用.

**Comment by wangzilinn** [comment]
搜狗输入法8.3，sublime3176，无论是开着搜狗直接进软件，还是打开sublime后从别的输入法切换到搜狗，均会卡死

**Comment by heimareed** [comment]
https://github.com/zcodes/IMESupport/issues/2#issuecomment-411269527
同样的问题，我把搜狗禁用了只用win10自带输入法可行。看来搜狗要离我远去了……

**Comment by konman750** [comment]
到处找解决方案，同样卡死没脾气

**Comment by heimareed** [comment]
被逼无奈，换了QQ输入法，Win10下正常使用。两种输入法使用上基本相同，但是感觉QQ确实比不上搜狗。

**Comment by zcodes** [comment]
最新版在 Window 10, Win7 上使用 系统自带输入法、QQ拼音、搜狗拼音测试可以

**Comment by zcodes** [comment]
@heimareed 最新的又调整了一下代码，目前测试来看问题就是打开 st 后需要喝口咖啡等一下，等插件彻底加载完毕，然后再输入中文定位就准确了，如果太急，会有不准的那么一下下...

**Comment by heimareed** [comment]
@zcodes 优秀~我回头试下。最近有点想放弃Bug10回退到Win7。Bug10主要体现在有时候莫名卡，原因是磁盘使用率100%。还有就是感觉无线网非常慢（开网页20s），换有线测试正常。之前没发现这些问题~哎，总之有点闹心。
