### ISSUE TITLE
win10字体缩放之后，跟随存在错位

### ISSUE THREAD

**Issue by tianhe117** [zcodes/IMESupport#3]
4K屏幕缩放200%，输入法跟随会错位，回复100%缩放就正常了

**Comment by TomatoFryEggs** [comment]
缩放125，出现错位，忘修复。

**Comment by zcodes** [comment]
这个问题尝试修复了一下，我这测试能够处理屏幕缩放了@TomatoFryEggs @tianhe117 可以试一下最新提交的版本

**Comment by TomatoFryEggs** [comment]
@zcodes 感谢，测试成功！
