### ISSUE TITLE
Not work after updating to the last commit

### ISSUE THREAD

**Issue by csJd** [zcodes/IMESupport#4]
as described, is there any way to fix this?

使用`git pull`更新到最新commit后插件无效，Build 3143

**Comment by csJd** [comment]
使用`git pul`更新到最新commit后插件无效，Build 3143

**Comment by zcodes** [comment]
能把问题说的清楚一点吗？还有你的操作系统是win 10？64还是32？

**Comment by csJd** [comment]
win10 x64 我重新安装sublime后现在又可以用了，是我这边的问题
