### ISSUE TITLE
输入框变大

### ISSUE THREAD

**Issue by zh-ray** [zcodes/IMESupport#8]
windows 10 + build 3176 屏幕为175%的缩放
正常输入，按下Esc取消输入时，下次输入时输入框就会放大一倍
![image](https://user-images.githubusercontent.com/16232711/45345906-46324e00-b5da-11e8-8826-7e018c66ca85.png)

**Comment by Mick-Brujah** [comment]
话说更新的修复脚本是需要手动执行吗？

**Comment by zcodes** [comment]
@zh-ray 试试最新版本，是不是还这样？

**Comment by zcodes** [comment]
@Mick-Brujah 可以直接使用Git克隆或者下载覆盖
