### ISSUE TITLE
Win 8.1 可以用嗎?

### ISSUE THREAD

**Issue by Kotsuha** [zcodes/IMESupport#9]
您好，不好意思對 DLL 方面的事情不是很懂，請問一下
Win 8.1 是否不能用呢?

我把 repo clone 到 Data\Packages 底下
重啟 Sublime Text 跳出以下訊息

> plugin_host.exe - 無法找到輸入點
> 
> 無法找到程序輸入點 GetDpiForSystem (在動態連結程式庫 D:\PortableApps\Sublime Text\Sublime Text x64 portable version\Sublime Text Build 3170 x64\Data\Packages\IMESupport\imesupport_hook_x64.dll)。

**Comment by zcodes** [comment]
GetDpiForSystem api 最小需求： Windows 10, version 1607 [desktop apps only]

**Comment by Kotsuha** [comment]
原来如此，谢谢回复

**Comment by zcodes** [comment]
@Kotsuha 最新版应该支持Win8， 我在Win7上测试可以用

**Comment by Kotsuha** [comment]
@zcodes 刚测试了一下，确实可以用了，感谢！
另想请问之前 readme 有写有用暂时性的做法修复 Toggle Side Bar 造成的定位不准，那个是先拿掉了吗？刚试了一下无效果

**Comment by Kotsuha** [comment]
不，我的意思是 Ctrl+K, Ctrl+B 启用/关闭 side bar 造成的定位不准，之前看 readme 说有修，现在呢？因为我 Ctrl+K, Ctrl+B 以后定位仍是不准的
